/**
 * api/index.ts - Vercel Serverless Function Entry
 *
 * Uses a STATIC import for the React Router SSR build so that
 * Vercel's static file tracer (@vercel/nft) can automatically detect
 * and bundle ALL dependencies (including @hono/node-server).
 *
 * Dynamic imports break Vercel's file tracer, causing ERR_MODULE_NOT_FOUND.
 */
import { getRequestListener } from '@hono/node-server';
import { createRequestHandler } from 'react-router';

// We import the SSR build generated by Vite/React Router.
// During esbuild, this will be marked as external and passed to Vercel NFT.
import * as build from '../build/server/index.js';

import { app } from '../__create/app';

// Create the React Router SSR request handler once at module level
const reactRouterHandler = createRequestHandler(build, 'production');

// Mount React Router SSR as catch-all for non-API routes
app.all('*', async (c) => {
  const url = new URL(c.req.url);
  const pathname = url.pathname;

  console.log(`[SSR] Handling request: ${c.req.method} ${pathname}`);

  // API routes are already handled by the mounted routes on `app`
  if (pathname.startsWith('/api/')) {
    console.log(`[SSR] Path ${pathname} starts with /api/, returning 404`);
    return c.notFound();
  }

  console.log(`[SSR] Calling reactRouterHandler for ${pathname}...`);
  const startTime = Date.now();

  try {
    // Add a manual timeout to prevent the whole function from hanging
    const timeoutPromise = new Promise((_, reject) => 
      setTimeout(() => reject(new Error('SSR Timeout (20s reached)')), 20000)
    );

    const result = await Promise.race([
      reactRouterHandler(c.req.raw),
      timeoutPromise
    ]) as Response;

    const duration = Date.now() - startTime;
    console.log(`[SSR] reactRouterHandler finished in ${duration}ms with status ${result.status}`);
    return result;
  } catch (err: any) {
    const duration = Date.now() - startTime;
    console.error(`[SSR ERROR] after ${duration}ms:`, err?.message);
    
    return c.html(
      `<html><body style="font-family:sans-serif;padding:40px;max-width:800px;margin:auto">
        <h2 style="color:#dc2626">SSR Error — ${err?.message}</h2>
        <p>This error occurred during Server-Side Rendering after ${duration}ms.</p>
        <pre style="background:#f1f5f9;padding:16px;border-radius:8px;overflow:auto;font-size:13px">${err?.stack || 'No stack trace available'}</pre>
        <hr/><p style="color:#64748b">Check Vercel logs for more details.</p>
       </body></html>`,
      500,
    );
  }
});

console.log('Server initialization complete. DATABASE_URL is', process.env.DATABASE_URL ? 'PRESENT' : 'MISSING');

// Vercel Serverless Functions running in Node.js ONLY need the default export.
// Do not use hono/vercel's handle() as it causes 504 timeouts on Node 20.
// Use getRequestListener from @hono/node-server instead.
export default getRequestListener(app.fetch);
