/**
 * api/index.ts - Vercel Serverless Function Entry
 *
 * Uses a STATIC import for the React Router SSR build so that
 * Vercel's static file tracer (@vercel/nft) can automatically detect
 * and bundle ALL dependencies (including @hono/node-server).
 *
 * Dynamic imports break Vercel's file tracer, causing ERR_MODULE_NOT_FOUND.
 */
import { Hono } from 'hono';
import { getRequestListener } from '@hono/node-server';
import { createRequestHandler } from 'react-router';

// We import the SSR build generated by Vite/React Router.
import * as build from '../build/server/index.js';
import { app as apiApp } from '../__create/app';

// Create a CLEAN Hono instance for the server entry
// This avoids any potential hangs in the global middlewares of apiApp
const app = new Hono();

// Mount the API app specifically on /api
app.route('/', apiApp);

// Create the React Router SSR request handler
const reactRouterHandler = createRequestHandler(build, 'production');

// Mount React Router SSR as catch-all for non-matched routes (like /)
app.all('*', async (c) => {
  const url = new URL(c.req.url);
  const pathname = url.pathname;

  console.log(`[SSR ENTRY] Handling: ${c.req.method} ${pathname}`);

  // Skip if it's an API route (already handled or 404)
  if (pathname.startsWith('/api/')) {
    return c.notFound();
  }

  console.log(`[SSR ENTRY] Invoking React Router for ${pathname}...`);
  const startTime = Date.now();

  try {
    const timeoutPromise = new Promise((_, reject) => 
      setTimeout(() => reject(new Error('SSR Timeout (15s reached)')), 15000)
    );

    const result = await Promise.race([
      reactRouterHandler(c.req.raw),
      timeoutPromise
    ]) as Response;

    console.log(`[SSR ENTRY] Finished in ${Date.now() - startTime}ms`);
    return result;
  } catch (err: any) {
    console.error(`[SSR ENTRY ERROR]:`, err?.message);
    return c.html(
      `<html><body style="font-family:sans-serif;padding:40px;max-width:800px;margin:auto">
        <h2 style="color:#dc2626">SSR Execution Error — ${err?.message}</h2>
        <pre style="background:#f1f5f9;padding:16px;border-radius:8px;overflow:auto;font-size:13px">${err?.stack}</pre>
       </body></html>`,
      500
    );
  }
});

console.log('Server initialization complete. DATABASE_URL is', process.env.DATABASE_URL ? 'PRESENT' : 'MISSING');

// Vercel Serverless Functions running in Node.js ONLY need the default export.
// Do not use hono/vercel's handle() as it causes 504 timeouts on Node 20.
// Use getRequestListener from @hono/node-server instead.
export default getRequestListener(app.fetch);
